---
title: "Peco demo"
author: "Seongchun Yang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

This script is meant to test **peco**, a supervised approach for predicting continuous cell cycle phase in scRNAseq data analysis.

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = '/project/', echo = F, warning = F, message = F)
```

# Preliminary look

```{r data}
data('training_human')
data('sce_top101genes')
sce_top101genes <- data_transform_quantile(sce_top101genes,ncores=6)
```

```{r pred}
pred_top101genes <- cycle_npreg_outsample(
    Y_test=sce_top101genes,
    sigma_est=training_human$sigma[rownames(sce_top101genes),],
    funs_est=training_human$cellcycle_function[rownames(sce_top101genes)],
    method.trend="trendfilter",
    ncores=6,
    get_trend_estimates=FALSE)
```

```{r plot_per_gene}
plot(y=assay(pred_top101genes$Y,"cpm_quantNormed")["ENSG00000170312",],
     x=colData(pred_top101genes$Y)$theta_shifted, main = "CDK1",
     xlab = "FUCCI phase",
     ylab = "quantile normalized expression",
     axes = F)
axis(2); axis(1,at=c(0,pi/2, pi, 3*pi/2, 2*pi),
              labels=c(0,expression(pi/2), expression(pi), expression(3*pi/2),
                       expression(2*pi)))
points(y=training_human$cellcycle_function[["ENSG00000170312"]](seq(0,2*pi, length.out=100)),
       x=seq(0,2*pi, length.out=100), col = "blue", pch =16)
```

# SessionInfo

```{r sessioninfo}
sessionInfo()
```